name: warp-proxy

services:
  warp:
    image: zenexas/warp-cli:latest
    restart: unless-stopped
    container_name: warp-proxy
    environment:
      LICENSE: "${WARP_LICENSE:-}"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "${WARP_PROXY_HOST:-127.0.0.1}:${WARP_PORT_START:-40001}:40000"
